networks:
  dashboard-network:
    driver: overlay

services:
  # Main dashboard application
  docker-swarm-dashboard:
    image: ghcr.io/heckenmann/docker-swarm-dashboard:master
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DSD_VERSION_CHECK_ENABLED: 'true'
    networks:
      - dashboard-network
  # Prometheus node-exporter for node metrics
  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global
      labels:
        - "dsd.node-exporter=true"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - dashboard-network
  # Google cadvisor for container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
      labels:
        - "dsd.cadvisor=true"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - dashboard-network