name: API Build and Healthcheck

env:
  WORKING_DIRECTORY: ./server-src

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build Go application
        run: go build -o docker-swarm-dashboard
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Start application
        run: ./docker-swarm-dashboard & sleep 3
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Test health endpoint
        run: curl -sSf http://localhost:8080/health | grep -q 'OK'

      - name: Stop application
        run: pkill docker-swarm-dashboard || true